name: Main
on: push
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - name: Install and Build 🔧
        run: | # Install npm packages and build the Storybook files
          yarn
          yarn test
          yarn prettier:check
          yarn build
          yarn copy-readme
          yarn build-doc
          CI=false yarn build-demo
          mkdir -p ./out/docs
          mv ./packages/core/docs/index.html ./packages/core/docs/index.htm
          mv ./packages/demo/app/index.html ./packages/demo/app/index.htm
          mv ./packages/core/docs/ ./out/
          mv ./packages/demo/app/* ./out/
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: out
          CLEAN: true
          SINGLE_COMMIT: true
          # TARGET_FOLDER: docs # The folder that we serve our Storybook files
